import Head from 'next/head';
import TwitterLogin from '@/components/twitterLogin';
import MisskeyLogin from '@/components/misskeyLogin';
import styles from '@/styles/Home.module.css';
import React, { createContext, useState } from 'react';

export const twIsLoginContext = createContext<IsLoginContextProps>({
  isLogin: false,
  setIsLogin: () => {},
});
export const mkIsLoginContext = createContext<IsLoginContextProps>({
  isLogin: false,
  setIsLogin: () => {},
});

const Home = () => {
  const [twIsLogin, setTwIsLogin] = useState<boolean>(false);
  const [mkIsLogin, setMkIsLogin] = useState<boolean>(false);
  const [postingContent, setPostingContent] = useState<string>('');
  const canPosting = twIsLogin && mkIsLogin;

  const onChangePostingContent = (
    event: React.ChangeEvent<HTMLTextAreaElement>
  ): void => {
    setPostingContent(event.target.value);
  };

  const login = async (postingContent: string, canPosting: boolean) => {
    if (!canPosting) return;

    const res = await fetch('/api/post', {
      method: 'POST',
      body: JSON.stringify({
        content: postingContent,
      }),
    });
    if (res.status !== 200) {
      console.error(`failed to post. status: ${res.status}`);

      return;
    }

    setPostingContent('');

    return;
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>CaffeBruncher</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>CaffeBruncher</h1>

        <div className={styles.login}>
          <twIsLoginContext.Provider
            value={{
              isLogin: twIsLogin,
              setIsLogin: setTwIsLogin,
            }}
          >
            <TwitterLogin />
          </twIsLoginContext.Provider>

          <mkIsLoginContext.Provider
            value={{
              isLogin: mkIsLogin,
              setIsLogin: setMkIsLogin,
            }}
          >
            <MisskeyLogin />
          </mkIsLoginContext.Provider>
        </div>
        <div>
          <textarea
            value={postingContent}
            disabled={!canPosting}
            onChange={onChangePostingContent}
          ></textarea>
          <button
            type='submit'
            disabled={!canPosting}
            onClick={() => {
              login(postingContent, canPosting);
            }}
          >
            Send
          </button>
        </div>
      </main>
    </div>
  );
};

export default Home;
